server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters: # Filtro por defecto de todas las requests realizadas al gateway
        - name: LogFilter
      discovery:
        Locator:
          enabled: true
      routes:
        - id: course
          uri: lb://courses
          predicates:
            - Path=/api/v1/courses/**
        - id: student
          uri: lb://student
          predicates:
            - Path=/api/v1/students/**

info:
  application:
     name: gateway
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

management:
  endpoints:
    gateway:
      enablesd: true
        
  endpoint:
    web:
      expose:
        include: gateway
